# Generated by Qodo Gen
import subprocess
from .k8s_tools import call_kubectl

# Dependencies:
# pip install pytest-mock
import pytest

# Command without 'kubectl' prefix is properly prefixed
def test_command_without_kubectl_prefix(mocker):
    # Arrange
    mock_subprocess = mocker.patch('subprocess.check_output')
    mock_subprocess.return_value = b'mocked output'
    command = 'get pods'

    # Act
    result = call_kubectl(command)

    # Assert
    mock_subprocess.assert_called_once_with(['kubectl', 'get', 'pods'])
    assert result == b'mocked output'


# Empty command string handling
def test_empty_command_string(mocker):
    # Arrange
    mock_subprocess = mocker.patch('subprocess.check_output')
    mock_subprocess.return_value = b''
    command = ''

    result = call_kubectl(command)

    # Assert
    mock_subprocess.assert_called_once_with(['kubectl', ''])
    assert result == b''